#========================================================================
# Copyright Universidade Federal do Espirito Santo (Ufes)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

version: "3.8"

services:
  # web app
  boca-web:
    environment:
      # database configuration
      # privileged user password
      - BOCA_DB_SUPER_PASSWORD=superpass
    ports:
      - 8000:80

  # online judge
  # boca-jail:

  # database
  boca-db:
    image: postgres:14-alpine
    environment:
      # database configuration
      # privileged user password
      - POSTGRES_PASSWORD=superpass
    healthcheck:
      # determine whether or not it is healthy
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s # interval between health checks
      timeout: 5s # timeout for each health checking
      retries: 20 # how many times retries
      start_period: 5s # estimated time to boot

  # api
  boca-api:
    image: boca-api
    depends_on:
      boca-db:
        condition: service_healthy
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: docker/dev/api/Dockerfile
      args:
        - ENV_FILE=./docker/dev/api/.env
    env_file:
      - ./docker/dev/api/.env

    restart: unless-stopped
    command: node index.js

  boca-adminer:
    image: adminer:latest
    environment:
      - ADMINER_DEFAULT_SERVER=boca-db
    ports:
      - 8080:8080
