wikiEd: testador.c contribuicao.c editor.c listaContribuicoes.c listaEditores.c listaLinks.c listaPaginas.c
	gcc -ggdb -std=c99 -Wall -Werror -Wformat=0 -Wno-unused-const-variable -o wiked.out *.c

clean:
	rm -f *.o a.out core wiked.out *.txt